---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: csns
spec:
  accessModes:
  - ReadWriteOnce
  # - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage