---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: bggapp
  template:
    metadata:
      name: bggapp-pod
      namespace: bggns
      labels:
        app: bggapp
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: app-port
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-svc
spec:
  # type: ClusterIP
  # type: NodePort
  type: LoadBalancer
  selector:
    app: bggapp
  ports:
  - port: 80
    targetPort: app-port
